config = {
    "extract_class_label": 1,
    "extract_continuous_label": 0,
    "extract_eeg": 1,
    "eeg_folder": "eeg",
    "eeg_config": {
        "sampling_frequency": 250,
        "window_sec": 5,
        "hop_sec": 5,
        "buffer_sec": 5,
        "num_electrodes": 8,
        "interest_bands": [(4, 8), (8, 10), (10, 13), (13, 20), (20, 30)],
        "channel_slice": {"eeg": slice(0, 8)},
        "features": ["eeg_PLI"],
        "filter_type": "butter",
        "filter_order": 4,
        "f_trans_interest_bands": [[4, 8], [8, 10], [10, 13], [13, 20], [20, 30]],
        "sfreq": 250,
        "pli_feature_mode": "delta_pli",
    },
    "save_npy": 1,
    "npy_folder": "compacted_EEG",
    "dataset_name": "Risk_EEG",
    "root_directory": r"C:\Users\云瑾\Desktop\data",
    "raw_data_folder": "SIEEG",
    "label_file": "minor_scale_2_gai.xlsx",
    "output_root_directory": r"C:\Users\云瑾\Desktop\data\Data_Processed",
    "emotion_list": ["SI", "SAS", "SDS"],
    "multiplier": {
        "eeg_raw": 1,
        "eeg_DE": 1,
        "continuous_label": 1,
    },
    "feature_dimension": {
        "eeg_raw": (2000,),
        "eeg_DE": (40,),
        "eeg_RP": (40,),
        "eeg_FE": (40,),
        "eeg_PLI": (140,),
        "class_label": (1,),
    },
    "max_epoch": 50,
    "min_epoch": 0,
    "early_stopping": 20,
    "load_best_at_each_epoch": 1,
    "time_delay": 0,
    "metrics": ["mae", "rmse", "r2", "pcc", "ccc"],
    "save_plot": 1,
    "experiments": {
        "Exp_DeltaPLI_PLIEncoder_GRU_RegOnly_LearnableLoss": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "gru_gate": 0.05,
            "learning_rate": 2e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 1e-4,
            "patience": 4,
            "early_stopping": 8,
            "loss_weighting": "homoscedastic_uncertainty",
        },
        "Exp_DeltaPLI_PLIEncoder_RegOnly_LearnableLoss_NoGRU": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "gru_gate": 0.05,
            "learning_rate": 2e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 1e-4,
            "patience": 4,
            "early_stopping": 8,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_GRU_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "gru_gate": 0.05,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "gru_gate": 0.05,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.25,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_AntiOverfit_v1_Drop035": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_AntiOverfit_v1_Drop035_Gate010": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.10,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_AntiOverfit_v1_Drop035_Gate010_lr5e5": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 5e-5,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 4,
            "early_stopping": 6,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.10,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_AntiOverfit_Drop035": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_AntiOverfit_Drop035_Gate010": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.10,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_AntiOverfit_Drop035_Gate010_lr5e5": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 5e-5,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 4,
            "early_stopping": 6,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.10,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_Layer2": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 2,
            "tct_num_heads": 4,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_Heads8": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 1,
            "tct_num_heads": 8,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCTLite_RegOnly_LearnableLoss_Layer2_Heads8": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.35,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.20,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "num_tct_layers": 2,
            "tct_num_heads": 8,
            "tct_ffn_dim": 128,
            "tct_dropout": 0.15,
            "tct_gate": 0.05,
            "temporal_pos_embed": True,
            "temporal_attention_pooling": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": False,
            "use_tcn_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "tcn_gate": 0.05,
            "tcn_channels": 64,
            "tcn_kernel_size": 3,
            "tcn_dilations": [1, 2, 4],
            "tcn_dropout": 0.20,
            "tcn_pooling": "attention",
            "tcn_residual": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_RegOnly_LearnableLoss_AntiOverfit_v1_Gate010": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": False,
            "use_tcn_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "tcn_gate": 0.10,
            "tcn_channels": 64,
            "tcn_kernel_size": 3,
            "tcn_dilations": [1, 2, 4],
            "tcn_dropout": 0.20,
            "tcn_pooling": "attention",
            "tcn_residual": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_Gate010_StdRatio025_Lambda002_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": False,
            "use_tcn_lite": True,
            "use_parallel_multiscale_tcn": False,
            "use_temporal_block_graph": False,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "tcn_gate": 0.10,
            "tcn_channels": 64,
            "tcn_kernel_size": 3,
            "tcn_dilations": [1, 2, 4],
            "tcn_dropout": 0.20,
            "tcn_pooling": "attention",
            "tcn_residual": True,
            "use_std_ratio_loss": True,
            "target_std_ratio": 0.25,
            "lambda_std": 0.02,
            "based_on": "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_RegOnly_LearnableLoss_AntiOverfit_v1_Gate010",
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_ParallelMS_TCN_D124_Gate010_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.45,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": False,
            "use_tcn_lite": False,
            "use_parallel_multiscale_tcn": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.30,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "tcn_gate": 0.10,
            "parallel_tcn_gate": 0.10,
            "parallel_tcn_dilations": [1, 2, 4],
            "parallel_tcn_kernel_size": 3,
            "parallel_tcn_channels": 64,
            "parallel_tcn_dropout": 0.20,
            "parallel_tcn_pooling": "attention",
            "parallel_tcn_residual": True,
            "scale_fusion": "softmax",
            "branch_pooling": "attention",
            "based_on": "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_RegOnly_LearnableLoss_AntiOverfit_v1_Gate010",
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TCNLite_RegOnly_LearnableLoss_AntiOverfit_v1_Gate010_Drop040": {
            "features": ["eeg_PLI"],
            "num_chan": 28,
            "thickness": 5,
            "huber_weight": 0.70,
            "rank_weight": 0.30,
            "learning_rate": 1e-4,
            "cnn1d_dropout": 0.40,
            "weight_decay": 5e-4,
            "patience": 3,
            "early_stopping": 5,
            "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False,
            "use_tct_lite": False,
            "use_tcn_lite": True,
            "use_band_edge_attention": True,
            "attn_scale": 0.1,
            "attention_dropout": 0.25,
            "lambda_attn": 0.01,
            "best_score_mode": "val_mae",
            "tcn_gate": 0.10,
            "tcn_channels": 64,
            "tcn_kernel_size": 3,
            "tcn_dilations": [1, 2, 4],
            "tcn_dropout": 0.15,
            "tcn_pooling": "attention",
            "tcn_residual": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TemporalBlockGraph_D1_Gate010_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"], "num_chan": 28, "thickness": 5,
            "huber_weight": 0.70, "rank_weight": 0.30,
            "learning_rate": 1e-4, "cnn1d_dropout": 0.45, "weight_decay": 5e-4,
            "patience": 3, "early_stopping": 5, "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False, "use_tct_lite": False, "use_tcn_lite": False,
            "use_temporal_block_graph": True, "use_band_edge_attention": True,
            "attn_scale": 0.1, "attention_dropout": 0.30, "lambda_attn": 0.01,
            "best_score_mode": "val_mae", "graph_gate": 0.10, "edge_distances": [1],
            "graph_dropout": 0.20, "graph_pooling": "attention", "graph_residual": True,
            "use_self_loop": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TemporalBlockGraph_D12_Gate010_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"], "num_chan": 28, "thickness": 5,
            "huber_weight": 0.70, "rank_weight": 0.30,
            "learning_rate": 1e-4, "cnn1d_dropout": 0.45, "weight_decay": 5e-4,
            "patience": 3, "early_stopping": 5, "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False, "use_tct_lite": False, "use_tcn_lite": False,
            "use_temporal_block_graph": True, "use_band_edge_attention": True,
            "attn_scale": 0.1, "attention_dropout": 0.30, "lambda_attn": 0.01,
            "best_score_mode": "val_mae", "graph_gate": 0.10, "edge_distances": [1, 2],
            "graph_dropout": 0.20, "graph_pooling": "attention", "graph_residual": True,
            "use_self_loop": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TemporalBlockGraph_D124_Gate010_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"], "num_chan": 28, "thickness": 5,
            "huber_weight": 0.70, "rank_weight": 0.30,
            "learning_rate": 1e-4, "cnn1d_dropout": 0.45, "weight_decay": 5e-4,
            "patience": 3, "early_stopping": 5, "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False, "use_tct_lite": False, "use_tcn_lite": False,
            "use_temporal_block_graph": True, "use_band_edge_attention": True,
            "attn_scale": 0.1, "attention_dropout": 0.30, "lambda_attn": 0.01,
            "best_score_mode": "val_mae", "graph_gate": 0.10, "edge_distances": [1, 2, 4],
            "graph_dropout": 0.20, "graph_pooling": "attention", "graph_residual": True,
            "use_self_loop": True,
        },
        "Exp_DeltaPLI_PLIEncoder_BandEdgeAttn_TemporalBlockGraph_D1248_Gate010_RegOnly_LearnableLoss_AntiOverfit_v1": {
            "features": ["eeg_PLI"], "num_chan": 28, "thickness": 5,
            "huber_weight": 0.70, "rank_weight": 0.30,
            "learning_rate": 1e-4, "cnn1d_dropout": 0.45, "weight_decay": 5e-4,
            "patience": 3, "early_stopping": 5, "loss_weighting": "homoscedastic_uncertainty",
            "use_gru": False, "use_tct_lite": False, "use_tcn_lite": False,
            "use_temporal_block_graph": True, "use_band_edge_attention": True,
            "attn_scale": 0.1, "attention_dropout": 0.30, "lambda_attn": 0.01,
            "best_score_mode": "val_mae", "graph_gate": 0.10, "edge_distances": [1, 2, 4, 8],
            "graph_dropout": 0.20, "graph_pooling": "attention", "graph_residual": True,
            "use_self_loop": True,
        },
    },
}
